project_id = "puls-dev"

[api]
port = 54321
schemas = [
  "public",
  "graphql_public",
  "puls_audit",
  "puls_calc",
  "puls_app",
  "puls_core",
  "puls_integration",
  "puls_performance",
  "puls_workflow",
]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
