/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPerformansRouteImport } from './routes/_app/performans'
import { Route as AppMenuRouteImport } from './routes/_app/menu'
import { Route as AppMasrafRouteImport } from './routes/_app/masraf'
import { Route as AppIzinRouteImport } from './routes/_app/izin'
import { Route as AppErpRouteImport } from './routes/_app/erp'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCalisanlarRouteImport } from './routes/_app/calisanlar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerformansRoute = AppPerformansRouteImport.update({
  id: '/performans',
  path: '/performans',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppMasrafRoute = AppMasrafRouteImport.update({
  id: '/masraf',
  path: '/masraf',
  getParentRoute: () => AppRoute,
} as any)
const AppIzinRoute = AppIzinRouteImport.update({
  id: '/izin',
  path: '/izin',
  getParentRoute: () => AppRoute,
} as any)
const AppErpRoute = AppErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalisanlarRoute = AppCalisanlarRouteImport.update({
  id: '/calisanlar',
  path: '/calisanlar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calisanlar': typeof AppCalisanlarRoute
  '/dashboard': typeof AppDashboardRoute
  '/erp': typeof AppErpRoute
  '/izin': typeof AppIzinRoute
  '/masraf': typeof AppMasrafRoute
  '/menu': typeof AppMenuRoute
  '/performans': typeof AppPerformansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calisanlar': typeof AppCalisanlarRoute
  '/dashboard': typeof AppDashboardRoute
  '/erp': typeof AppErpRoute
  '/izin': typeof AppIzinRoute
  '/masraf': typeof AppMasrafRoute
  '/menu': typeof AppMenuRoute
  '/performans': typeof AppPerformansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/calisanlar': typeof AppCalisanlarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/erp': typeof AppErpRoute
  '/_app/izin': typeof AppIzinRoute
  '/_app/masraf': typeof AppMasrafRoute
  '/_app/menu': typeof AppMenuRoute
  '/_app/performans': typeof AppPerformansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calisanlar'
    | '/dashboard'
    | '/erp'
    | '/izin'
    | '/masraf'
    | '/menu'
    | '/performans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/calisanlar'
    | '/dashboard'
    | '/erp'
    | '/izin'
    | '/masraf'
    | '/menu'
    | '/performans'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/calisanlar'
    | '/_app/dashboard'
    | '/_app/erp'
    | '/_app/izin'
    | '/_app/masraf'
    | '/_app/menu'
    | '/_app/performans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/performans': {
      id: '/_app/performans'
      path: '/performans'
      fullPath: '/performans'
      preLoaderRoute: typeof AppPerformansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masraf': {
      id: '/_app/masraf'
      path: '/masraf'
      fullPath: '/masraf'
      preLoaderRoute: typeof AppMasrafRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/izin': {
      id: '/_app/izin'
      path: '/izin'
      fullPath: '/izin'
      preLoaderRoute: typeof AppIzinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/erp': {
      id: '/_app/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof AppErpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calisanlar': {
      id: '/_app/calisanlar'
      path: '/calisanlar'
      fullPath: '/calisanlar'
      preLoaderRoute: typeof AppCalisanlarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalisanlarRoute: typeof AppCalisanlarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppErpRoute: typeof AppErpRoute
  AppIzinRoute: typeof AppIzinRoute
  AppMasrafRoute: typeof AppMasrafRoute
  AppMenuRoute: typeof AppMenuRoute
  AppPerformansRoute: typeof AppPerformansRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalisanlarRoute: AppCalisanlarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppErpRoute: AppErpRoute,
  AppIzinRoute: AppIzinRoute,
  AppMasrafRoute: AppMasrafRoute,
  AppMenuRoute: AppMenuRoute,
  AppPerformansRoute: AppPerformansRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
