/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSozlesmelerRouteImport } from './routes/_app/sozlesmeler'
import { Route as AppSirketKurulumRouteImport } from './routes/_app/sirket-kurulum'
import { Route as AppPozisyonlarRouteImport } from './routes/_app/pozisyonlar'
import { Route as AppPerformansParametreleriRouteImport } from './routes/_app/performans-parametreleri'
import { Route as AppPerformansRouteImport } from './routes/_app/performans'
import { Route as AppMenuRouteImport } from './routes/_app/menu'
import { Route as AppMasrafKategorileriRouteImport } from './routes/_app/masraf-kategorileri'
import { Route as AppMasrafRouteImport } from './routes/_app/masraf'
import { Route as AppKariyerRouteImport } from './routes/_app/kariyer'
import { Route as AppIzinTanimlariRouteImport } from './routes/_app/izin-tanimlari'
import { Route as AppIzinRouteImport } from './routes/_app/izin'
import { Route as AppIsDegerlemeRouteImport } from './routes/_app/is-degerleme'
import { Route as AppErpRouteImport } from './routes/_app/erp'
import { Route as AppEgitimRouteImport } from './routes/_app/egitim'
import { Route as AppDepartmanlarRouteImport } from './routes/_app/departmanlar'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCalisanlarRouteImport } from './routes/_app/calisanlar'
import { Route as AppAiKocRouteImport } from './routes/_app/ai-koc'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSozlesmelerRoute = AppSozlesmelerRouteImport.update({
  id: '/sozlesmeler',
  path: '/sozlesmeler',
  getParentRoute: () => AppRoute,
} as any)
const AppSirketKurulumRoute = AppSirketKurulumRouteImport.update({
  id: '/sirket-kurulum',
  path: '/sirket-kurulum',
  getParentRoute: () => AppRoute,
} as any)
const AppPozisyonlarRoute = AppPozisyonlarRouteImport.update({
  id: '/pozisyonlar',
  path: '/pozisyonlar',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformansParametreleriRoute =
  AppPerformansParametreleriRouteImport.update({
    id: '/performans-parametreleri',
    path: '/performans-parametreleri',
    getParentRoute: () => AppRoute,
  } as any)
const AppPerformansRoute = AppPerformansRouteImport.update({
  id: '/performans',
  path: '/performans',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppMasrafKategorileriRoute = AppMasrafKategorileriRouteImport.update({
  id: '/masraf-kategorileri',
  path: '/masraf-kategorileri',
  getParentRoute: () => AppRoute,
} as any)
const AppMasrafRoute = AppMasrafRouteImport.update({
  id: '/masraf',
  path: '/masraf',
  getParentRoute: () => AppRoute,
} as any)
const AppKariyerRoute = AppKariyerRouteImport.update({
  id: '/kariyer',
  path: '/kariyer',
  getParentRoute: () => AppRoute,
} as any)
const AppIzinTanimlariRoute = AppIzinTanimlariRouteImport.update({
  id: '/izin-tanimlari',
  path: '/izin-tanimlari',
  getParentRoute: () => AppRoute,
} as any)
const AppIzinRoute = AppIzinRouteImport.update({
  id: '/izin',
  path: '/izin',
  getParentRoute: () => AppRoute,
} as any)
const AppIsDegerlemeRoute = AppIsDegerlemeRouteImport.update({
  id: '/is-degerleme',
  path: '/is-degerleme',
  getParentRoute: () => AppRoute,
} as any)
const AppErpRoute = AppErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => AppRoute,
} as any)
const AppEgitimRoute = AppEgitimRouteImport.update({
  id: '/egitim',
  path: '/egitim',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmanlarRoute = AppDepartmanlarRouteImport.update({
  id: '/departmanlar',
  path: '/departmanlar',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalisanlarRoute = AppCalisanlarRouteImport.update({
  id: '/calisanlar',
  path: '/calisanlar',
  getParentRoute: () => AppRoute,
} as any)
const AppAiKocRoute = AppAiKocRouteImport.update({
  id: '/ai-koc',
  path: '/ai-koc',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-koc': typeof AppAiKocRoute
  '/calisanlar': typeof AppCalisanlarRoute
  '/dashboard': typeof AppDashboardRoute
  '/departmanlar': typeof AppDepartmanlarRoute
  '/egitim': typeof AppEgitimRoute
  '/erp': typeof AppErpRoute
  '/is-degerleme': typeof AppIsDegerlemeRoute
  '/izin': typeof AppIzinRoute
  '/izin-tanimlari': typeof AppIzinTanimlariRoute
  '/kariyer': typeof AppKariyerRoute
  '/masraf': typeof AppMasrafRoute
  '/masraf-kategorileri': typeof AppMasrafKategorileriRoute
  '/menu': typeof AppMenuRoute
  '/performans': typeof AppPerformansRoute
  '/performans-parametreleri': typeof AppPerformansParametreleriRoute
  '/pozisyonlar': typeof AppPozisyonlarRoute
  '/sirket-kurulum': typeof AppSirketKurulumRoute
  '/sozlesmeler': typeof AppSozlesmelerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-koc': typeof AppAiKocRoute
  '/calisanlar': typeof AppCalisanlarRoute
  '/dashboard': typeof AppDashboardRoute
  '/departmanlar': typeof AppDepartmanlarRoute
  '/egitim': typeof AppEgitimRoute
  '/erp': typeof AppErpRoute
  '/is-degerleme': typeof AppIsDegerlemeRoute
  '/izin': typeof AppIzinRoute
  '/izin-tanimlari': typeof AppIzinTanimlariRoute
  '/kariyer': typeof AppKariyerRoute
  '/masraf': typeof AppMasrafRoute
  '/masraf-kategorileri': typeof AppMasrafKategorileriRoute
  '/menu': typeof AppMenuRoute
  '/performans': typeof AppPerformansRoute
  '/performans-parametreleri': typeof AppPerformansParametreleriRoute
  '/pozisyonlar': typeof AppPozisyonlarRoute
  '/sirket-kurulum': typeof AppSirketKurulumRoute
  '/sozlesmeler': typeof AppSozlesmelerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai-koc': typeof AppAiKocRoute
  '/_app/calisanlar': typeof AppCalisanlarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departmanlar': typeof AppDepartmanlarRoute
  '/_app/egitim': typeof AppEgitimRoute
  '/_app/erp': typeof AppErpRoute
  '/_app/is-degerleme': typeof AppIsDegerlemeRoute
  '/_app/izin': typeof AppIzinRoute
  '/_app/izin-tanimlari': typeof AppIzinTanimlariRoute
  '/_app/kariyer': typeof AppKariyerRoute
  '/_app/masraf': typeof AppMasrafRoute
  '/_app/masraf-kategorileri': typeof AppMasrafKategorileriRoute
  '/_app/menu': typeof AppMenuRoute
  '/_app/performans': typeof AppPerformansRoute
  '/_app/performans-parametreleri': typeof AppPerformansParametreleriRoute
  '/_app/pozisyonlar': typeof AppPozisyonlarRoute
  '/_app/sirket-kurulum': typeof AppSirketKurulumRoute
  '/_app/sozlesmeler': typeof AppSozlesmelerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-koc'
    | '/calisanlar'
    | '/dashboard'
    | '/departmanlar'
    | '/egitim'
    | '/erp'
    | '/is-degerleme'
    | '/izin'
    | '/izin-tanimlari'
    | '/kariyer'
    | '/masraf'
    | '/masraf-kategorileri'
    | '/menu'
    | '/performans'
    | '/performans-parametreleri'
    | '/pozisyonlar'
    | '/sirket-kurulum'
    | '/sozlesmeler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-koc'
    | '/calisanlar'
    | '/dashboard'
    | '/departmanlar'
    | '/egitim'
    | '/erp'
    | '/is-degerleme'
    | '/izin'
    | '/izin-tanimlari'
    | '/kariyer'
    | '/masraf'
    | '/masraf-kategorileri'
    | '/menu'
    | '/performans'
    | '/performans-parametreleri'
    | '/pozisyonlar'
    | '/sirket-kurulum'
    | '/sozlesmeler'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ai-koc'
    | '/_app/calisanlar'
    | '/_app/dashboard'
    | '/_app/departmanlar'
    | '/_app/egitim'
    | '/_app/erp'
    | '/_app/is-degerleme'
    | '/_app/izin'
    | '/_app/izin-tanimlari'
    | '/_app/kariyer'
    | '/_app/masraf'
    | '/_app/masraf-kategorileri'
    | '/_app/menu'
    | '/_app/performans'
    | '/_app/performans-parametreleri'
    | '/_app/pozisyonlar'
    | '/_app/sirket-kurulum'
    | '/_app/sozlesmeler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sozlesmeler': {
      id: '/_app/sozlesmeler'
      path: '/sozlesmeler'
      fullPath: '/sozlesmeler'
      preLoaderRoute: typeof AppSozlesmelerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sirket-kurulum': {
      id: '/_app/sirket-kurulum'
      path: '/sirket-kurulum'
      fullPath: '/sirket-kurulum'
      preLoaderRoute: typeof AppSirketKurulumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pozisyonlar': {
      id: '/_app/pozisyonlar'
      path: '/pozisyonlar'
      fullPath: '/pozisyonlar'
      preLoaderRoute: typeof AppPozisyonlarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performans-parametreleri': {
      id: '/_app/performans-parametreleri'
      path: '/performans-parametreleri'
      fullPath: '/performans-parametreleri'
      preLoaderRoute: typeof AppPerformansParametreleriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performans': {
      id: '/_app/performans'
      path: '/performans'
      fullPath: '/performans'
      preLoaderRoute: typeof AppPerformansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masraf-kategorileri': {
      id: '/_app/masraf-kategorileri'
      path: '/masraf-kategorileri'
      fullPath: '/masraf-kategorileri'
      preLoaderRoute: typeof AppMasrafKategorileriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masraf': {
      id: '/_app/masraf'
      path: '/masraf'
      fullPath: '/masraf'
      preLoaderRoute: typeof AppMasrafRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kariyer': {
      id: '/_app/kariyer'
      path: '/kariyer'
      fullPath: '/kariyer'
      preLoaderRoute: typeof AppKariyerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/izin-tanimlari': {
      id: '/_app/izin-tanimlari'
      path: '/izin-tanimlari'
      fullPath: '/izin-tanimlari'
      preLoaderRoute: typeof AppIzinTanimlariRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/izin': {
      id: '/_app/izin'
      path: '/izin'
      fullPath: '/izin'
      preLoaderRoute: typeof AppIzinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/is-degerleme': {
      id: '/_app/is-degerleme'
      path: '/is-degerleme'
      fullPath: '/is-degerleme'
      preLoaderRoute: typeof AppIsDegerlemeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/erp': {
      id: '/_app/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof AppErpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/egitim': {
      id: '/_app/egitim'
      path: '/egitim'
      fullPath: '/egitim'
      preLoaderRoute: typeof AppEgitimRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departmanlar': {
      id: '/_app/departmanlar'
      path: '/departmanlar'
      fullPath: '/departmanlar'
      preLoaderRoute: typeof AppDepartmanlarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calisanlar': {
      id: '/_app/calisanlar'
      path: '/calisanlar'
      fullPath: '/calisanlar'
      preLoaderRoute: typeof AppCalisanlarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-koc': {
      id: '/_app/ai-koc'
      path: '/ai-koc'
      fullPath: '/ai-koc'
      preLoaderRoute: typeof AppAiKocRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiKocRoute: typeof AppAiKocRoute
  AppCalisanlarRoute: typeof AppCalisanlarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmanlarRoute: typeof AppDepartmanlarRoute
  AppEgitimRoute: typeof AppEgitimRoute
  AppErpRoute: typeof AppErpRoute
  AppIsDegerlemeRoute: typeof AppIsDegerlemeRoute
  AppIzinRoute: typeof AppIzinRoute
  AppIzinTanimlariRoute: typeof AppIzinTanimlariRoute
  AppKariyerRoute: typeof AppKariyerRoute
  AppMasrafRoute: typeof AppMasrafRoute
  AppMasrafKategorileriRoute: typeof AppMasrafKategorileriRoute
  AppMenuRoute: typeof AppMenuRoute
  AppPerformansRoute: typeof AppPerformansRoute
  AppPerformansParametreleriRoute: typeof AppPerformansParametreleriRoute
  AppPozisyonlarRoute: typeof AppPozisyonlarRoute
  AppSirketKurulumRoute: typeof AppSirketKurulumRoute
  AppSozlesmelerRoute: typeof AppSozlesmelerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiKocRoute: AppAiKocRoute,
  AppCalisanlarRoute: AppCalisanlarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmanlarRoute: AppDepartmanlarRoute,
  AppEgitimRoute: AppEgitimRoute,
  AppErpRoute: AppErpRoute,
  AppIsDegerlemeRoute: AppIsDegerlemeRoute,
  AppIzinRoute: AppIzinRoute,
  AppIzinTanimlariRoute: AppIzinTanimlariRoute,
  AppKariyerRoute: AppKariyerRoute,
  AppMasrafRoute: AppMasrafRoute,
  AppMasrafKategorileriRoute: AppMasrafKategorileriRoute,
  AppMenuRoute: AppMenuRoute,
  AppPerformansRoute: AppPerformansRoute,
  AppPerformansParametreleriRoute: AppPerformansParametreleriRoute,
  AppPozisyonlarRoute: AppPozisyonlarRoute,
  AppSirketKurulumRoute: AppSirketKurulumRoute,
  AppSozlesmelerRoute: AppSozlesmelerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
